# Generated by Django 6.0.2 on 2026-03-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='min_contribution',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
    ]
