# Generated by Django 6.0.2 on 2026-03-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='return_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_date',
            field=models.DateTimeField(blank=True, help_text='When payment was completed', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Payment Pending'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('failed', 'Payment Failed')], default='pending', help_text='Payment status for the booking', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_date',
            field=models.DateField(blank=True, help_text='Date when item can be picked up', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_location',
            field=models.TextField(blank=True, help_text='Location where item can be picked up'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_date',
            field=models.DateField(help_text='End date of the booking period'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup_time',
            field=models.TimeField(blank=True, help_text='Time when item can be picked up', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_date',
            field=models.DateField(help_text='Start date of the booking period'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved - Payment Pending'), ('paid', 'Paid - Ready for Pickup'), ('declined', 'Declined'), ('active', 'Active (Checked Out)'), ('completed', 'Completed (Returned)'), ('cancelled', 'Cancelled'), ('overdue', 'Overdue')], default='pending', max_length=20),
        ),
    ]
