"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
import sys 
from pathlib import Path
from django.contrib.messages import constants as messages

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_ROOT = BASE_DIR

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-change-me-in-env')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'True').lower() == 'true'

# CSRF settings
CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8000',
    'http://localhost:8000',
]
DJANGO_CSRF_TRUSTED_ORIGINS = os.getenv('DJANGO_CSRF_TRUSTED_ORIGINS', '')
if DJANGO_CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS.extend(
        [origin.strip() for origin in DJANGO_CSRF_TRUSTED_ORIGINS.split(',') if origin.strip()]
    )

# Secure cookies only when not running in local DEBUG mode (Render serves over HTTPS)
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = False
SESSION_COOKIE_SECURE = not DEBUG


DJANGO_ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', '')
ALLOWED_HOSTS = [
    '127.0.0.1',
    'testserver',
    "localhost",
]

if DJANGO_ALLOWED_HOSTS:
    ALLOWED_HOSTS.extend(
        [host.strip() for host in DJANGO_ALLOWED_HOSTS.split(',') if host.strip()]
    )

# Render sets this automatically to the service's onrender.com hostname
RENDER_EXTERNAL_HOSTNAME = os.getenv('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)
    CSRF_TRUSTED_ORIGINS.append(f'https://{RENDER_EXTERNAL_HOSTNAME}')

# Render terminates TLS at its proxy and forwards plain HTTP internally, so
# Django needs this to correctly recognize the request as secure.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = not DEBUG

# Ensure the parent directory that contains the `apps` package is on sys.path.
# The local apps package lives at backend/apps, so add the backend folder.
sys.path.insert(0, os.path.join(BASE_DIR, 'backend'))

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth', #authentication app offered by django
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.sites',
    'django.contrib.staticfiles', 
    'rest_framework',
    'corsheaders',
    'anymail',
    'verify_email.apps.VerifyEmailConfig',
     # local apps
    'apps.accounts', 
    'apps.bookings',
    'apps.campaigns',
    'apps.core',
    'apps.items',
    'apps.messaging',
    'apps.payments',
    'apps.reviews',
    
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'frontend')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.core.context_processors.payments_status',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.getenv('KNOT_DB_PATH', str(BASE_DIR / 'db.sqlite3')),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/


# Static files - point to css, js, assets folders
STATICFILES_DIRS = [
    BASE_DIR / 'css',
    BASE_DIR / 'static',
    BASE_DIR / 'assets',
]

STATIC_URL = '/static/'
STATIC_ROOT = Path(os.getenv('KNOT_STATIC_ROOT', str(BASE_DIR / 'staticfiles')))

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Media files (uploaded user content such as item photos)
MEDIA_URL = '/media/'
MEDIA_ROOT = Path(os.getenv('KNOT_MEDIA_ROOT', str(BASE_DIR / 'media')))

# Authentication settings
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'user_dashboard'
LOGOUT_REDIRECT_URL = 'index'

# Sites framework
SITE_ID = 1

# Message tags styling

MESSAGE_TAGS = {
    messages.ERROR: 'danger',
    messages.SUCCESS: 'success',
    messages.INFO: 'info',
    messages.WARNING: 'warning',
}

# Custom user model
AUTH_USER_MODEL = 'accounts.CustomUser'

# When False, new signups are auto-verified and can use the site immediately
# instead of waiting on an email link — useful for a demo deployment where
# visitors (e.g. reviewers) shouldn't be blocked on email deliverability.
REQUIRE_EMAIL_VERIFICATION = os.getenv('REQUIRE_EMAIL_VERIFICATION', 'True').lower() == 'true'

# Email settings
# Render (like most PaaS free tiers) blocks outbound SMTP entirely, so raw
# Gmail SMTP only works for local development. In production, set
# RESEND_API_KEY and email is sent over HTTPS via Resend instead.
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')  # Set via environment variable
# Without a timeout, a blocked/slow outbound SMTP connection hangs the
# request indefinitely until the app server force-kills the worker (which
# surfaces as an ugly 500 instead of the graceful "email failed" message
# the signup view already handles). Fail fast instead.
EMAIL_TIMEOUT = 10

RESEND_API_KEY = os.getenv('RESEND_API_KEY', '')
if RESEND_API_KEY:
    EMAIL_BACKEND = 'anymail.backends.resend.EmailBackend'
    ANYMAIL = {'RESEND_API_KEY': RESEND_API_KEY}
    # resend.dev is Resend's shared sandbox sender domain, usable with zero
    # setup; swap in a verified custom domain via DEFAULT_FROM_EMAIL once one
    # is set up in the Resend dashboard.
    DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'Knot <onboarding@resend.dev>')
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    # Gmail's SMTP relay requires (or silently rewrites) the From address to
    # match the authenticated account, so this must track EMAIL_HOST_USER.
    DEFAULT_FROM_EMAIL = f'Knot <{EMAIL_HOST_USER}>' if EMAIL_HOST_USER else 'Knot <noreply@knot.com>'


# Email verification settings for django-verify-email
VERIFICATION_HTML_TEMPLATE = 'emails/verify_email.html'  # Template for the email
VERIFICATION_SUCCESS_TEMPLATE = 'registration/verification_success.html'  # Success page
VERIFICATION_FAILED_TEMPLATE = 'registration/verification_failed.html'  # Failed page
EXPIRE_AFTER = 1800  # 30 minutes in seconds
MAX_RETRIES = 3  # Maximum number of retries

# PayHero Settings
PAYHERO_USERNAME = os.getenv('PAYHERO_USERNAME', '')
PAYHERO_API_KEY = os.getenv('PAYHERO_API_KEY', '')
PAYHERO_API_SECRET = os.getenv('PAYHERO_API_SECRET', '')
PAYHERO_WEBHOOK_SECRET = os.getenv('PAYHERO_WEBHOOK_SECRET', '')
PAYHERO_ACCOUNT_NUMBER = os.getenv('PAYHERO_ACCOUNT_NUMBER', '')
PAYHERO_CHANNEL_ID = os.getenv('PAYHERO_CHANNEL_ID', '')

# IMPORTANT: Use your ngrok URL
NGROK_URL = os.getenv('NGROK_URL', 'http://127.0.0.1:8000')

PAYHERO_BASE_URL = 'https://backend.payhero.co.ke'
PAYHERO_PAYMENT_URL = f'https://app.payhero.co.ke/lipwa/{PAYHERO_CHANNEL_ID}'
PAYHERO_CALLBACK_URL = f'{NGROK_URL}/api/campaigns/payment-callback/'
BOOKING_PAYHERO_CALLBACK_URL = f'{NGROK_URL}/api/bookings/payment-callback/'
SITE_URL = NGROK_URL

# Optional: Test mode (set to False when ready for real payments)
PAYHERO_TEST_MODE = os.getenv('PAYHERO_TEST_MODE', 'False').lower() == 'true'


# Session settings
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 1209600  # 2 weeks in seconds
SESSION_COOKIE_HTTPONLY = True
SESSION_SAVE_EVERY_REQUEST = True  # This helps keep the session alive

# DRF settings: JSON-only API responses to avoid browsable API template dependency
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}