# Generated by Django 6.0.2 on 2026-03-22 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('booking_request', 'Booking Request'), ('booking_approved', 'Booking Approved'), ('booking_declined', 'Booking Declined'), ('booking_reminder', 'Booking Reminder'), ('booking_overdue', 'Booking Overdue'), ('campaign_funded', 'Campaign Funded'), ('campaign_expiring', 'Campaign Expiring'), ('new_message', 'New Message'), ('new_review', 'New Review'), ('payment_received', 'Payment Received'), ('payout_completed', 'Payout Completed'), ('system', 'System Notification')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('related_url', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Knot', max_length=100)),
                ('tagline', models.CharField(default='Tying Communities Together Through Shared Resources', max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('enable_payments', models.BooleanField(default=True)),
                ('enable_messaging', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField(blank=True)),
                ('total_users', models.IntegerField(default=0)),
                ('total_items', models.IntegerField(default=0)),
                ('total_campaigns', models.IntegerField(default=0)),
                ('total_contributions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='sites.site')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
