# Generated by Django 6.0.2 on 2026-03-22 13:53

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('admin_request_status', models.CharField(choices=[('none', 'No Request'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='none', help_text='Status of admin request', max_length=20)),
                ('admin_request_reason', models.TextField(blank=True, help_text='Reason for requesting admin access', null=True)),
                ('admin_request_date', models.DateTimeField(blank=True, help_text='When admin was requested', null=True)),
                ('admin_request_review_date', models.DateTimeField(blank=True, help_text='When request was reviewed', null=True)),
                ('admin_request_review_notes', models.TextField(blank=True, help_text='Notes from admin review', null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Kenyan phone number format (e.g., 0712345678 or 254712345678)', max_length=15, null=True)),
                ('verification_level', models.IntegerField(choices=[(0, 'Unverified'), (1, 'Email Verified'), (2, 'Phone Verified'), (3, 'ID Verified')], default=0, help_text='Current verification tier of the user')),
                ('email_verified', models.BooleanField(default=False, help_text='Whether email has been verified')),
                ('phone_verified', models.BooleanField(default=False, help_text='Whether phone number has been verified')),
                ('id_verified', models.BooleanField(default=False, help_text='Whether government ID has been verified')),
                ('profile_picture', models.ImageField(blank=True, help_text='User profile picture (optional)', null=True, upload_to='profile_pics/')),
                ('bio', models.TextField(blank=True, help_text='Short biography about the user', max_length=500)),
                ('location', models.CharField(blank=True, help_text='Neighborhood or general location', max_length=100)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating from reviews (0.00 to 5.00)', max_digits=3)),
                ('total_reviews', models.IntegerField(default=0, help_text='Total number of reviews received')),
                ('successful_bookings', models.IntegerField(default=0, help_text='Number of successfully completed bookings as borrower')),
                ('successful_lendings', models.IntegerField(default=0, help_text='Number of successfully completed bookings as lender/steward')),
                ('cancelled_bookings', models.IntegerField(default=0, help_text='Number of bookings cancelled by user')),
                ('date_joined', models.DateTimeField(auto_now_add=True, help_text='When user registered')),
                ('last_active', models.DateTimeField(default=django.utils.timezone.now, help_text='Last time user was active on platform')),
                ('admin_request_reviewed_by', models.ForeignKey(blank=True, help_text='Which admin reviewed this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_admin_requests', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Verification Token',
                'verbose_name_plural': 'Email Verification Tokens',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password Reset Token',
                'verbose_name_plural': 'Password Reset Tokens',
            },
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['username'], name='accounts_cu_usernam_ab560e_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='accounts_cu_email_5ce40b_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['verification_level'], name='accounts_cu_verific_a38386_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['-average_rating'], name='accounts_cu_average_5efac1_idx'),
        ),
    ]
