# Generated by Django 6.0.2 on 2026-03-22 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Category name (e.g., 'Tools', 'Electronics')", max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly version of the name', max_length=120, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of what belongs in this category')),
                ('icon', models.CharField(blank=True, help_text="Font Awesome icon class (e.g., 'fa-tools')", max_length=50)),
                ('image', models.ImageField(blank=True, help_text='Category image for display', null=True, upload_to='categories/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Item name/title', max_length=200)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('description', models.TextField(help_text='Detailed description of the item')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags for search', max_length=500)),
                ('condition', models.CharField(choices=[('new', 'New'), ('like_new', 'Like New'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('borrowed', 'Borrowed'), ('maintenance', 'Under Maintenance'), ('retired', 'Retired')], default='available', max_length=20)),
                ('location_details', models.TextField(help_text='Where to pick up the item')),
                ('daily_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Optional rental fee per day (KES)', max_digits=10, null=True)),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Security deposit amount (KES)', max_digits=10, null=True)),
                ('max_borrow_days', models.IntegerField(default=14, help_text='Maximum days allowed per booking')),
                ('total_bookings', models.IntegerField(default=0, help_text='Total number of times borrowed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acquired_item', to='campaigns.campaign')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='items.category')),
                ('host_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='campaigns.organization')),
                ('steward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='item_images/')),
                ('is_primary', models.BooleanField(default=False, help_text='Whether this is the main display image')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='items.item')),
            ],
            options={
                'verbose_name': 'Item Image',
                'verbose_name_plural': 'Item Images',
                'ordering': ['-is_primary', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Why this item is needed and how it will be used')),
                ('estimated_cost', models.DecimalField(decimal_places=2, help_text='Estimated cost in KES', max_digits=10)),
                ('votes', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('campaign_created', 'Campaign Created')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to='items.category')),
                ('suggested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_suggestions', to=settings.AUTH_USER_MODEL)),
                ('voters', models.ManyToManyField(blank=True, related_name='voted_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item Suggestion',
                'verbose_name_plural': 'Item Suggestions',
                'ordering': ['-votes', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['slug'], name='items_item_slug_d94d1c_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['status'], name='items_item_status_819478_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['category', 'status'], name='items_item_categor_1a7dcd_idx'),
        ),
    ]
